/**
 * Main execution for CPU tests
 *
 * Auto-generated by scripts/generate_cpu_tests.py
 * Do not edit manually!
 *
 * @author Niklas Vainio
 * @date   2026-02-08
 */

#include "CpuTest.hpp"
#include "common/logging.hpp"
#include <format>

/**
 * Assert that \p `expr` has the desires value, and return false if the
 * assertion fails.
 */
#define AssertEq(expr, value)                                                  \
    do                                                                         \
    {                                                                          \
        const auto result = (expr);                                            \
        if (result != value)                                                   \
        {                                                                      \
            LogError("%s",                                                     \
                     std::format(                                              \
                         "Expected {} == {}, got {}", #expr, #value, result)   \
                         .c_str());                                            \
            return false;                                                      \
        }                                                                      \
    } while (0)

namespace Gbpp::Test
{

bool CpuTest::run()
{
}

namespace cpu_tests
{

}

} // namespace Gbpp::Test