/**
 * CPU instruction implementations.
 *
 * File skeleton generated by scripts/generate_instruction_code.py
 *
 * @author Niklas Vainio
 * @date   2026-02-01
 */

#include "Cpu.hpp"
#include "common/logging.hpp"
#include <format>

namespace Gbpp::Backend
{

void Cpu::instruction_ILLEGAL()
{
    /*
     * Catch-all for illegal opcodes. Log an error and do nothing.
     */
    LogError("Encoutered invalid opcode 0x%02X at PC = 0x%04X", opcode, pc - 1);
    current_instruction_asm = std::format("ILLEGAL {:02X}", opcode);
}

/*
 * ============================================================================
 * Unprefixed Instructions
 * ============================================================================
 */

void Cpu::instruction_00_NOP()
{
    /*
     * NOP
     * Flags: - - - -
     * Cycles: 4
     */
    current_instruction_asm = std::format("NOP");
}

void Cpu::instruction_01_LD()
{
    /*
     * LD BC, n16
     * Flags: - - - -
     * Cycles: 12
     */
    const uint16_t n16 = fetch_16();
    set_BC(n16);

    current_instruction_asm = std::format("LD BC, {:04X}", n16);
}

void Cpu::instruction_02_LD()
{
    /*
     * LD [BC], A
     * Flags: - - - -
     * Cycles: 8
     */
    write_8(get_BC(), A);

    current_instruction_asm = std::format("LD !BC, A");
}

void Cpu::instruction_03_INC()
{
    /*
     * INC BC
     * Flags: - - - -
     * Cycles: 8
     */
    set_BC(get_BC() + 1);

    current_instruction_asm = std::format("INC BC");
}

void Cpu::instruction_04_INC()
{
    /*
     * INC B
     * Flags: Z 0 H -
     * Cycles: 4
     */
    B++;

    set_Z(B == 0);
    set_N(0);
    set_H((B & 0x0f) == 0);
    current_instruction_asm = std::format("INC B");
}

void Cpu::instruction_05_DEC()
{
    /*
     * DEC B
     * Flags: Z 1 H -
     * Cycles: 4
     */
    B--;

    set_Z(B == 0);
    set_N(1);
    set_H((B & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC B");
}

void Cpu::instruction_06_LD()
{
    /*
     * LD B, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    B = n8;

    current_instruction_asm = std::format("LD B, {:02X}", n8);
}

void Cpu::instruction_07_RLCA()
{
    /*
     * RLCA
     * Flags: 0 0 0 C
     * Cycles: 4
     */
    const bool bit_7 = A >> 7;
    A = (A << 1) | bit_7;

    set_Z(0);
    set_N(0);
    set_H(0);
    set_C(bit_7);
    current_instruction_asm = std::format("RLCA");
}

void Cpu::instruction_08_LD()
{
    /*
     * LD [a16], SP
     * Flags: - - - -
     * Cycles: 20
     */
    const uint16_t a16 = fetch_16();
    write_16(a16, sp);

    current_instruction_asm = std::format("LD !{:04X}, SP", a16);
}

void Cpu::instruction_09_ADD()
{
    /*
     * ADD HL, BC
     * Flags: - 0 H C
     * Cycles: 8
     */
    const uint16_t op1 = get_HL();
    const uint16_t op2 = get_BC();
    const uint32_t sum = op1 + op2;

    set_HL(sum);

    set_N(0);
    set_H((op1 & 0x0fff) + (op2 & 0x0fff) > 0x0fff);
    set_C(sum & 0x10000);
    current_instruction_asm = std::format("ADD HL, BC");
}

void Cpu::instruction_0A_LD()
{
    /*
     * LD A, [BC]
     * Flags: - - - -
     * Cycles: 8
     */
    A = read_8(get_BC());

    current_instruction_asm = std::format("LD A, !BC");
}

void Cpu::instruction_0B_DEC()
{
    /*
     * DEC BC
     * Flags: - - - -
     * Cycles: 8
     */
    set_BC(get_BC() - 1);

    current_instruction_asm = std::format("DEC BC");
}

void Cpu::instruction_0C_INC()
{
    /*
     * INC C
     * Flags: Z 0 H -
     * Cycles: 4
     */
    C++;

    set_Z(C == 0);
    set_N(0);
    set_H((C & 0x0f) == 0);
    current_instruction_asm = std::format("INC C");
}

void Cpu::instruction_0D_DEC()
{
    /*
     * DEC C
     * Flags: Z 1 H -
     * Cycles: 4
     */
    C--;

    set_Z(C == 0);
    set_N(1);
    set_H((C & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC C");
}

void Cpu::instruction_0E_LD()
{
    /*
     * LD C, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    C = n8;

    current_instruction_asm = std::format("LD C, {:02X}", n8);
}

void Cpu::instruction_0F_RRCA()
{
    /*
     * RRCA
     * Flags: 0 0 0 C
     * Cycles: 4
     */
    bool bit_0 = A & 1;
    A = (bit_0 << 7) | (A >> 1);

    set_Z(0);
    set_N(0);
    set_H(0);
    set_C(bit_0);
    current_instruction_asm = std::format("RRCA");
}

void Cpu::instruction_10_STOP()
{
    /*
     * FIXME - handle this properly
     * STOP n8
     * Flags: - - - -
     * Cycles: 4
     */
    LogWarning("STOP is not fully implemented!");
    const uint8_t n8 = fetch_8();
    current_instruction_asm = std::format("STOP {:02X}", n8);
}

void Cpu::instruction_11_LD()
{
    /*
     * LD DE, n16
     * Flags: - - - -
     * Cycles: 12
     */
    const uint16_t n16 = fetch_16();
    set_DE(n16);

    current_instruction_asm = std::format("LD DE, {:04X}", n16);
}

void Cpu::instruction_12_LD()
{
    /*
     * LD [DE], A
     * Flags: - - - -
     * Cycles: 8
     */
    write_8(get_DE(), A);

    current_instruction_asm = std::format("LD !DE, A");
}

void Cpu::instruction_13_INC()
{
    /*
     * INC DE
     * Flags: - - - -
     * Cycles: 8
     */
    set_DE(get_DE() + 1);

    current_instruction_asm = std::format("INC DE");
}

void Cpu::instruction_14_INC()
{
    /*
     * INC D
     * Flags: Z 0 H -
     * Cycles: 4
     */
    D++;

    set_Z(D == 0);
    set_N(0);
    set_H((D & 0x0f) == 0);
    current_instruction_asm = std::format("INC D");
}

void Cpu::instruction_15_DEC()
{
    /*
     * DEC D
     * Flags: Z 1 H -
     * Cycles: 4
     */
    D--;

    set_Z(D == 0);
    set_N(1);
    set_H((D & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC D");
}

void Cpu::instruction_16_LD()
{
    /*
     * LD D, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    D = n8;

    current_instruction_asm = std::format("LD D, {:02X}", n8);
}

void Cpu::instruction_17_RLA()
{
    /*
     * RLA
     * Flags: 0 0 0 C
     * Cycles: 4
     */
    const bool bit_7 = A >> 7;
    A = (A << 1) | get_C();

    set_Z(0);
    set_N(0);
    set_H(0);
    set_C(bit_7);
    current_instruction_asm = std::format("RLA ");
}

void Cpu::instruction_18_JR()
{
    /*
     * JR e8
     * Flags: - - - -
     * Cycles: 12
     */
    const int8_t e8 = static_cast<int8_t>(fetch_8());
    pc += e8;

    current_instruction_asm = std::format("JR {:04X}", pc);
}

void Cpu::instruction_19_ADD()
{
    /*
     * ADD HL, DE
     * Flags: - 0 H C
     * Cycles: 8
     */
    const uint16_t op1 = get_HL();
    const uint16_t op2 = get_DE();
    const uint32_t sum = op1 + op2;

    set_HL(sum);

    set_N(0);
    set_H((op1 & 0x0fff) + (op2 & 0x0fff) > 0x0fff);
    set_C(sum & 0x10000);
    current_instruction_asm = std::format("ADD HL, DE");
}

void Cpu::instruction_1A_LD()
{
    /*
     * LD A, [DE]
     * Flags: - - - -
     * Cycles: 8
     */
    A = read_8(get_DE());

    current_instruction_asm = std::format("LD A, !DE");
}

void Cpu::instruction_1B_DEC()
{
    /*
     * DEC DE
     * Flags: - - - -
     * Cycles: 8
     */
    set_DE(get_DE() - 1);

    current_instruction_asm = std::format("DEC DE");
}

void Cpu::instruction_1C_INC()
{
    /*
     * INC E
     * Flags: Z 0 H -
     * Cycles: 4
     */
    E++;

    set_Z(E == 0);
    set_N(0);
    set_H((E & 0x0f) == 0);
    current_instruction_asm = std::format("INC E");
}

void Cpu::instruction_1D_DEC()
{
    /*
     * DEC E
     * Flags: Z 1 H -
     * Cycles: 4
     */
    E--;

    set_Z(E == 0);
    set_N(1);
    set_H((E & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC E");
}

void Cpu::instruction_1E_LD()
{
    /*
     * LD E, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    E = n8;

    current_instruction_asm = std::format("LD E, {:02X}", n8);
}

void Cpu::instruction_1F_RRA()
{
    /*
     * RRA
     * Flags: 0 0 0 C
     * Cycles: 4
     */
    bool bit_0 = A & 1;
    A = (get_C() << 7) | (A >> 1);

    set_Z(0);
    set_N(0);
    set_H(0);
    set_C(bit_0);
    current_instruction_asm = std::format("RRA ");
}

void Cpu::instruction_20_JR()
{
    /*
     * JR NZ, e8
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("JR NZ, e8");
}

void Cpu::instruction_21_LD()
{
    /*
     * LD HL, n16
     * Flags: - - - -
     * Cycles: 12
     */
    const uint16_t n16 = fetch_16();
    set_HL(n16);

    current_instruction_asm = std::format("LD HL, {:04X}", n16);
}

void Cpu::instruction_22_LD()
{
    /*
     * LD [HL+], A
     * Flags: - - - -
     * Cycles: 8
     */
    write_8(get_HL(), A);
    set_HL(get_HL() + 1);

    current_instruction_asm = std::format("LDI !HL, A");
}

void Cpu::instruction_23_INC()
{
    /*
     * INC HL
     * Flags: - - - -
     * Cycles: 8
     */
    set_HL(get_HL() + 1);

    current_instruction_asm = std::format("INC HL");
}

void Cpu::instruction_24_INC()
{
    /*
     * INC H
     * Flags: Z 0 H -
     * Cycles: 4
     */
    H++;

    set_Z(H == 0);
    set_N(0);
    set_H((H & 0x0f) == 0);
    current_instruction_asm = std::format("INC H");
}

void Cpu::instruction_25_DEC()
{
    /*
     * DEC H
     * Flags: Z 1 H -
     * Cycles: 4
     */
    H--;

    set_Z(H == 0);
    set_N(1);
    set_H((H & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC H");
}

void Cpu::instruction_26_LD()
{
    /*
     * LD H, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    H = n8;

    current_instruction_asm = std::format("LD H, {:02X}", n8);
}

void Cpu::instruction_27_DAA()
{
    /*
     * FIXME - implement this
     *
     * DAA
     * Flags: Z - 0 C
     * Cycles: 4
     */
    LogWarning("DAA is unimplemented!");
    current_instruction_asm = std::format("DAA");
}

void Cpu::instruction_28_JR()
{
    /*
     * JR Z, e8
     * Flags: - - - -
     * Cycles: 8/12
     */
    const int8_t e8 = static_cast<int8_t>(fetch_8());
    const uint16_t dest = pc + e8;

    if (get_Z())
    {
        pc = dest;
        num_cycles_elapsed += 4;
    }

    current_instruction_asm = std::format("JR Z, {:04X}", dest);
}

void Cpu::instruction_29_ADD()
{
    /*
     * ADD HL, HL
     * Flags: - 0 H C
     * Cycles: 8
     */
    const uint16_t op1 = get_HL();
    const uint16_t op2 = get_HL();
    const uint32_t sum = op1 + op2;

    set_HL(sum);

    set_N(0);
    set_H((op1 & 0x0fff) + (op2 & 0x0fff) > 0x0fff);
    set_C(sum & 0x10000);
    current_instruction_asm = std::format("ADD HL, HL");
}

void Cpu::instruction_2A_LD()
{
    /*
     * LD A, [HL+]
     * Flags: - - - -
     * Cycles: 8
     */
    A = read_8(get_HL());
    set_HL(get_HL() + 1);

    current_instruction_asm = std::format("LDI A, !HL");
}

void Cpu::instruction_2B_DEC()
{
    /*
     * DEC HL
     * Flags: - - - -
     * Cycles: 8
     */
    set_HL(get_HL() - 1);

    current_instruction_asm = std::format("DEC HL");
}

void Cpu::instruction_2C_INC()
{
    /*
     * INC L
     * Flags: Z 0 H -
     * Cycles: 4
     */
    L++;

    set_Z(L == 0);
    set_N(0);
    set_H((L & 0x0f) == 0);
    current_instruction_asm = std::format("INC L");
}

void Cpu::instruction_2D_DEC()
{
    /*
     * DEC L
     * Flags: Z 1 H -
     * Cycles: 4
     */
    L--;

    set_Z(L == 0);
    set_N(1);
    set_H((L & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC L");
}

void Cpu::instruction_2E_LD()
{
    /*
     * LD L, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    L = n8;

    current_instruction_asm = std::format("LD L, {:02X}", n8);
}

void Cpu::instruction_2F_CPL()
{
    /*
     * CPL
     * Flags: - 1 1 -
     * Cycles: 4
     */
    A = ~A;

    set_N(1);
    set_H(1);
    current_instruction_asm = std::format("CPL ");
}

void Cpu::instruction_30_JR()
{
    /*
     * JR NC, e8
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("JR NC, e8");
}

void Cpu::instruction_31_LD()
{
    /*
     * LD SP, n16
     * Flags: - - - -
     * Cycles: 12
     */
    const uint16_t n16 = fetch_16();
    sp = n16;

    current_instruction_asm = std::format("LD SP, {:04X}", n16);
}

void Cpu::instruction_32_LD()
{
    /*
     * LD [HL-], A
     * Flags: - - - -
     * Cycles: 8
     */
    write_8(get_HL(), A);
    set_HL(get_HL() - 1);

    current_instruction_asm = std::format("LDD !HL, A");
}

void Cpu::instruction_33_INC()
{
    /*
     * INC SP
     * Flags: - - - -
     * Cycles: 8
     */
    sp++;

    current_instruction_asm = std::format("INC SP");
}

void Cpu::instruction_34_INC()
{
    /*
     * INC [HL]
     * Flags: Z 0 H -
     * Cycles: 12
     */
    const uint8_t result = read_8(get_HL()) + 1;
    write_8(get_HL(), result);

    set_Z(result == 0);
    set_N(0);
    set_H((result & 0x0f) == 0);
    current_instruction_asm = std::format("INC !HL");
}

void Cpu::instruction_35_DEC()
{
    /*
     * DEC [HL]
     * Flags: Z 1 H -
     * Cycles: 12
     */
    const uint8_t result = read_8(get_HL()) - 1;
    write_8(get_HL(), result);

    set_Z(result == 0);
    set_N(1);
    set_H((result & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC !HL");
}

void Cpu::instruction_36_LD()
{
    /*
     * LD [HL], n8
     * Flags: - - - -
     * Cycles: 12
     */
    const uint8_t n8 = fetch_8();
    write_8(get_HL(), n8);

    current_instruction_asm = std::format("LD !HL, {:02X}", n8);
}

void Cpu::instruction_37_SCF()
{
    /*
     * SCF
     * Flags: - 0 0 1
     * Cycles: 4
     */
    set_N(0);
    set_H(0);
    set_C(1);
    current_instruction_asm = std::format("SCF ");
}

void Cpu::instruction_38_JR()
{
    /*
     * JR C, e8
     * Flags: - - - -
     * Cycles: 8
     */
    const int8_t e8 = static_cast<int8_t>(fetch_8());
    const uint16_t dest = pc + e8;

    if (get_C())
    {
        pc = dest;
        num_cycles_elapsed += 4;
    }

    current_instruction_asm = std::format("JR C, {:04X}", dest);
}

void Cpu::instruction_39_ADD()
{
    /*
     * ADD HL, SP
     * Flags: - 0 H C
     * Cycles: 8
     */
    const uint16_t op1 = get_HL();
    const uint16_t op2 = sp;
    const uint32_t sum = op1 + op2;

    set_HL(sum);

    set_N(0);
    set_H((op1 & 0x0fff) + (op2 & 0x0fff) > 0x0fff);
    set_C(sum & 0x10000);
    current_instruction_asm = std::format("ADD HL, SP");
}

void Cpu::instruction_3A_LD()
{
    /*
     * LD A, [HL-]
     * Flags: - - - -
     * Cycles: 8
     */
    A = read_8(get_HL());
    set_HL(get_HL() - 1);

    current_instruction_asm = std::format("LDD A, !HL");
}

void Cpu::instruction_3B_DEC()
{
    /*
     * DEC SP
     * Flags: - - - -
     * Cycles: 8
     */
    sp--;

    current_instruction_asm = std::format("DEC SP");
}

void Cpu::instruction_3C_INC()
{
    /*
     * INC A
     * Flags: Z 0 H -
     * Cycles: 4
     */
    A++;

    set_Z(A == 0);
    set_N(0);
    set_H((A & 0x0f) == 0);
    current_instruction_asm = std::format("INC A");
}

void Cpu::instruction_3D_DEC()
{
    /*
     * DEC A
     * Flags: Z 1 H -
     * Cycles: 4
     */
    A--;

    set_Z(A == 0);
    set_N(1);
    set_H((A & 0x0f) == 0xf);
    current_instruction_asm = std::format("DEC A");
}

void Cpu::instruction_3E_LD()
{
    /*
     * LD A, n8
     * Flags: - - - -
     * Cycles: 8
     */
    const uint8_t n8 = fetch_8();
    A = n8;

    current_instruction_asm = std::format("LD A, {:02X}", n8);
}

void Cpu::instruction_3F_CCF()
{
    /*
     * CCF
     * Flags: - 0 0 C
     * Cycles: 4
     */
    set_N(0);
    set_H(0);
    set_C(0);
    current_instruction_asm = std::format("CCF ");
}

void Cpu::instruction_40_LD()
{
    /*
     * LD B, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, B");
}

void Cpu::instruction_41_LD()
{
    /*
     * LD B, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, C");
}

void Cpu::instruction_42_LD()
{
    /*
     * LD B, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, D");
}

void Cpu::instruction_43_LD()
{
    /*
     * LD B, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, E");
}

void Cpu::instruction_44_LD()
{
    /*
     * LD B, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, H");
}

void Cpu::instruction_45_LD()
{
    /*
     * LD B, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, L");
}

void Cpu::instruction_46_LD()
{
    /*
     * LD B, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD B, !HL");
}

void Cpu::instruction_47_LD()
{
    /*
     * LD B, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD B, A");
}

void Cpu::instruction_48_LD()
{
    /*
     * LD C, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, B");
}

void Cpu::instruction_49_LD()
{
    /*
     * LD C, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, C");
}

void Cpu::instruction_4A_LD()
{
    /*
     * LD C, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, D");
}

void Cpu::instruction_4B_LD()
{
    /*
     * LD C, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, E");
}

void Cpu::instruction_4C_LD()
{
    /*
     * LD C, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, H");
}

void Cpu::instruction_4D_LD()
{
    /*
     * LD C, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, L");
}

void Cpu::instruction_4E_LD()
{
    /*
     * LD C, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD C, !HL");
}

void Cpu::instruction_4F_LD()
{
    /*
     * LD C, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD C, A");
}

void Cpu::instruction_50_LD()
{
    /*
     * LD D, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, B");
}

void Cpu::instruction_51_LD()
{
    /*
     * LD D, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, C");
}

void Cpu::instruction_52_LD()
{
    /*
     * LD D, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, D");
}

void Cpu::instruction_53_LD()
{
    /*
     * LD D, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, E");
}

void Cpu::instruction_54_LD()
{
    /*
     * LD D, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, H");
}

void Cpu::instruction_55_LD()
{
    /*
     * LD D, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, L");
}

void Cpu::instruction_56_LD()
{
    /*
     * LD D, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD D, !HL");
}

void Cpu::instruction_57_LD()
{
    /*
     * LD D, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD D, A");
}

void Cpu::instruction_58_LD()
{
    /*
     * LD E, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, B");
}

void Cpu::instruction_59_LD()
{
    /*
     * LD E, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, C");
}

void Cpu::instruction_5A_LD()
{
    /*
     * LD E, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, D");
}

void Cpu::instruction_5B_LD()
{
    /*
     * LD E, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, E");
}

void Cpu::instruction_5C_LD()
{
    /*
     * LD E, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, H");
}

void Cpu::instruction_5D_LD()
{
    /*
     * LD E, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, L");
}

void Cpu::instruction_5E_LD()
{
    /*
     * LD E, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD E, !HL");
}

void Cpu::instruction_5F_LD()
{
    /*
     * LD E, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD E, A");
}

void Cpu::instruction_60_LD()
{
    /*
     * LD H, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, B");
}

void Cpu::instruction_61_LD()
{
    /*
     * LD H, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, C");
}

void Cpu::instruction_62_LD()
{
    /*
     * LD H, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, D");
}

void Cpu::instruction_63_LD()
{
    /*
     * LD H, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, E");
}

void Cpu::instruction_64_LD()
{
    /*
     * LD H, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, H");
}

void Cpu::instruction_65_LD()
{
    /*
     * LD H, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, L");
}

void Cpu::instruction_66_LD()
{
    /*
     * LD H, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD H, !HL");
}

void Cpu::instruction_67_LD()
{
    /*
     * LD H, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD H, A");
}

void Cpu::instruction_68_LD()
{
    /*
     * LD L, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, B");
}

void Cpu::instruction_69_LD()
{
    /*
     * LD L, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, C");
}

void Cpu::instruction_6A_LD()
{
    /*
     * LD L, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, D");
}

void Cpu::instruction_6B_LD()
{
    /*
     * LD L, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, E");
}

void Cpu::instruction_6C_LD()
{
    /*
     * LD L, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, H");
}

void Cpu::instruction_6D_LD()
{
    /*
     * LD L, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, L");
}

void Cpu::instruction_6E_LD()
{
    /*
     * LD L, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD L, !HL");
}

void Cpu::instruction_6F_LD()
{
    /*
     * LD L, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD L, A");
}

void Cpu::instruction_70_LD()
{
    /*
     * LD [HL], B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, B");
}

void Cpu::instruction_71_LD()
{
    /*
     * LD [HL], C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, C");
}

void Cpu::instruction_72_LD()
{
    /*
     * LD [HL], D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, D");
}

void Cpu::instruction_73_LD()
{
    /*
     * LD [HL], E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, E");
}

void Cpu::instruction_74_LD()
{
    /*
     * LD [HL], H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, H");
}

void Cpu::instruction_75_LD()
{
    /*
     * LD [HL], L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, L");
}

void Cpu::instruction_76_HALT()
{
    /*
     * FIXME - implement this
     *
     * HALT
     * Flags: - - - -
     * Cycles: 4
     */
    LogWarning("HALT is unimplemented");
    current_instruction_asm = std::format("HALT");
}

void Cpu::instruction_77_LD()
{
    /*
     * LD [HL], A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD !HL, A");
}

void Cpu::instruction_78_LD()
{
    /*
     * LD A, B
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, B");
}

void Cpu::instruction_79_LD()
{
    /*
     * LD A, C
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, C");
}

void Cpu::instruction_7A_LD()
{
    /*
     * LD A, D
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, D");
}

void Cpu::instruction_7B_LD()
{
    /*
     * LD A, E
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, E");
}

void Cpu::instruction_7C_LD()
{
    /*
     * LD A, H
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, H");
}

void Cpu::instruction_7D_LD()
{
    /*
     * LD A, L
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, L");
}

void Cpu::instruction_7E_LD()
{
    /*
     * LD A, [HL]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD A, !HL");
}

void Cpu::instruction_7F_LD()
{
    /*
     * LD A, A
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("LD A, A");
}

void Cpu::instruction_80_ADD()
{
    /*
     * ADD A, B
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, B");
}

void Cpu::instruction_81_ADD()
{
    /*
     * ADD A, C
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, C");
}

void Cpu::instruction_82_ADD()
{
    /*
     * ADD A, D
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, D");
}

void Cpu::instruction_83_ADD()
{
    /*
     * ADD A, E
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, E");
}

void Cpu::instruction_84_ADD()
{
    /*
     * ADD A, H
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, H");
}

void Cpu::instruction_85_ADD()
{
    /*
     * ADD A, L
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, L");
}

void Cpu::instruction_86_ADD()
{
    /*
     * ADD A, [HL]
     * Flags: Z 0 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("ADD A, !HL");
}

void Cpu::instruction_87_ADD()
{
    /*
     * ADD A, A
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADD A, A");
}

void Cpu::instruction_88_ADC()
{
    /*
     * ADC A, B
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, B");
}

void Cpu::instruction_89_ADC()
{
    /*
     * ADC A, C
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, C");
}

void Cpu::instruction_8A_ADC()
{
    /*
     * ADC A, D
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, D");
}

void Cpu::instruction_8B_ADC()
{
    /*
     * ADC A, E
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, E");
}

void Cpu::instruction_8C_ADC()
{
    /*
     * ADC A, H
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, H");
}

void Cpu::instruction_8D_ADC()
{
    /*
     * ADC A, L
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, L");
}

void Cpu::instruction_8E_ADC()
{
    /*
     * ADC A, [HL]
     * Flags: Z 0 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("ADC A, !HL");
}

void Cpu::instruction_8F_ADC()
{
    /*
     * ADC A, A
     * Flags: Z 0 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("ADC A, A");
}

void Cpu::instruction_90_SUB()
{
    /*
     * SUB A, B
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, B");
}

void Cpu::instruction_91_SUB()
{
    /*
     * SUB A, C
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, C");
}

void Cpu::instruction_92_SUB()
{
    /*
     * SUB A, D
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, D");
}

void Cpu::instruction_93_SUB()
{
    /*
     * SUB A, E
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, E");
}

void Cpu::instruction_94_SUB()
{
    /*
     * SUB A, H
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, H");
}

void Cpu::instruction_95_SUB()
{
    /*
     * SUB A, L
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, L");
}

void Cpu::instruction_96_SUB()
{
    /*
     * SUB A, [HL]
     * Flags: Z 1 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SUB A, !HL");
}

void Cpu::instruction_97_SUB()
{
    /*
     * SUB A, A
     * Flags: 1 1 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("SUB A, A");
}

void Cpu::instruction_98_SBC()
{
    /*
     * SBC A, B
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, B");
}

void Cpu::instruction_99_SBC()
{
    /*
     * SBC A, C
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, C");
}

void Cpu::instruction_9A_SBC()
{
    /*
     * SBC A, D
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, D");
}

void Cpu::instruction_9B_SBC()
{
    /*
     * SBC A, E
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, E");
}

void Cpu::instruction_9C_SBC()
{
    /*
     * SBC A, H
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, H");
}

void Cpu::instruction_9D_SBC()
{
    /*
     * SBC A, L
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, L");
}

void Cpu::instruction_9E_SBC()
{
    /*
     * SBC A, [HL]
     * Flags: Z 1 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SBC A, !HL");
}

void Cpu::instruction_9F_SBC()
{
    /*
     * SBC A, A
     * Flags: Z 1 H -
     * Cycles: 4
     */

    current_instruction_asm = std::format("SBC A, A");
}

void Cpu::instruction_A0_AND()
{
    /*
     * AND A, B
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, B");
}

void Cpu::instruction_A1_AND()
{
    /*
     * AND A, C
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, C");
}

void Cpu::instruction_A2_AND()
{
    /*
     * AND A, D
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, D");
}

void Cpu::instruction_A3_AND()
{
    /*
     * AND A, E
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, E");
}

void Cpu::instruction_A4_AND()
{
    /*
     * AND A, H
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, H");
}

void Cpu::instruction_A5_AND()
{
    /*
     * AND A, L
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, L");
}

void Cpu::instruction_A6_AND()
{
    /*
     * AND A, [HL]
     * Flags: Z 0 1 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("AND A, !HL");
}

void Cpu::instruction_A7_AND()
{
    /*
     * AND A, A
     * Flags: Z 0 1 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("AND A, A");
}

void Cpu::instruction_A8_XOR()
{
    /*
     * XOR A, B
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, B");
}

void Cpu::instruction_A9_XOR()
{
    /*
     * XOR A, C
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, C");
}

void Cpu::instruction_AA_XOR()
{
    /*
     * XOR A, D
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, D");
}

void Cpu::instruction_AB_XOR()
{
    /*
     * XOR A, E
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, E");
}

void Cpu::instruction_AC_XOR()
{
    /*
     * XOR A, H
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, H");
}

void Cpu::instruction_AD_XOR()
{
    /*
     * XOR A, L
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, L");
}

void Cpu::instruction_AE_XOR()
{
    /*
     * XOR A, [HL]
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("XOR A, !HL");
}

void Cpu::instruction_AF_XOR()
{
    /*
     * XOR A, A
     * Flags: 1 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("XOR A, A");
}

void Cpu::instruction_B0_OR()
{
    /*
     * OR A, B
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, B");
}

void Cpu::instruction_B1_OR()
{
    /*
     * OR A, C
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, C");
}

void Cpu::instruction_B2_OR()
{
    /*
     * OR A, D
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, D");
}

void Cpu::instruction_B3_OR()
{
    /*
     * OR A, E
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, E");
}

void Cpu::instruction_B4_OR()
{
    /*
     * OR A, H
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, H");
}

void Cpu::instruction_B5_OR()
{
    /*
     * OR A, L
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, L");
}

void Cpu::instruction_B6_OR()
{
    /*
     * OR A, [HL]
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("OR A, !HL");
}

void Cpu::instruction_B7_OR()
{
    /*
     * OR A, A
     * Flags: Z 0 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("OR A, A");
}

void Cpu::instruction_B8_CP()
{
    /*
     * CP A, B
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, B");
}

void Cpu::instruction_B9_CP()
{
    /*
     * CP A, C
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, C");
}

void Cpu::instruction_BA_CP()
{
    /*
     * CP A, D
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, D");
}

void Cpu::instruction_BB_CP()
{
    /*
     * CP A, E
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, E");
}

void Cpu::instruction_BC_CP()
{
    /*
     * CP A, H
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, H");
}

void Cpu::instruction_BD_CP()
{
    /*
     * CP A, L
     * Flags: Z 1 H C
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, L");
}

void Cpu::instruction_BE_CP()
{
    /*
     * CP A, [HL]
     * Flags: Z 1 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("CP A, !HL");
}

void Cpu::instruction_BF_CP()
{
    /*
     * CP A, A
     * Flags: 1 1 0 0
     * Cycles: 4
     */

    current_instruction_asm = std::format("CP A, A");
}

void Cpu::instruction_C0_RET()
{
    /*
     * RET NZ
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RET NZ");
}

void Cpu::instruction_C1_POP()
{
    /*
     * POP BC
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("POP BC");
}

void Cpu::instruction_C2_JP()
{
    /*
     * JP NZ, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("JP NZ, a16");
}

void Cpu::instruction_C3_JP()
{
    /*
     * JP a16
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("JP a16");
}

void Cpu::instruction_C4_CALL()
{
    /*
     * CALL NZ, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("CALL NZ, a16");
}

void Cpu::instruction_C5_PUSH()
{
    /*
     * PUSH BC
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("PUSH BC");
}

void Cpu::instruction_C6_ADD()
{
    /*
     * ADD A, n8
     * Flags: Z 0 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("ADD A, n8");
}

void Cpu::instruction_C7_RST()
{
    /*
     * RST $00
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 00");
}

void Cpu::instruction_C8_RET()
{
    /*
     * RET Z
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RET Z");
}

void Cpu::instruction_C9_RET()
{
    /*
     * RET
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RET ");
}

void Cpu::instruction_CA_JP()
{
    /*
     * JP Z, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("JP Z, a16");
}

void Cpu::instruction_CC_CALL()
{
    /*
     * CALL Z, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("CALL Z, a16");
}

void Cpu::instruction_CD_CALL()
{
    /*
     * CALL a16
     * Flags: - - - -
     * Cycles: 24
     */

    current_instruction_asm = std::format("CALL a16");
}

void Cpu::instruction_CE_ADC()
{
    /*
     * ADC A, n8
     * Flags: Z 0 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("ADC A, n8");
}

void Cpu::instruction_CF_RST()
{
    /*
     * RST $08
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 08");
}

void Cpu::instruction_D0_RET()
{
    /*
     * RET NC
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RET NC");
}

void Cpu::instruction_D1_POP()
{
    /*
     * POP DE
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("POP DE");
}

void Cpu::instruction_D2_JP()
{
    /*
     * JP NC, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("JP NC, a16");
}

void Cpu::instruction_D4_CALL()
{
    /*
     * CALL NC, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("CALL NC, a16");
}

void Cpu::instruction_D5_PUSH()
{
    /*
     * PUSH DE
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("PUSH DE");
}

void Cpu::instruction_D6_SUB()
{
    /*
     * SUB A, n8
     * Flags: Z 1 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SUB A, n8");
}

void Cpu::instruction_D7_RST()
{
    /*
     * RST $10
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 10");
}

void Cpu::instruction_D8_RET()
{
    /*
     * RET C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RET C");
}

void Cpu::instruction_D9_RETI()
{
    /*
     * RETI
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RETI ");
}

void Cpu::instruction_DA_JP()
{
    /*
     * JP C, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("JP C, a16");
}

void Cpu::instruction_DC_CALL()
{
    /*
     * CALL C, a16
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("CALL C, a16");
}

void Cpu::instruction_DE_SBC()
{
    /*
     * SBC A, n8
     * Flags: Z 1 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SBC A, n8");
}

void Cpu::instruction_DF_RST()
{
    /*
     * RST $18
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 18");
}

void Cpu::instruction_E0_LDH()
{
    /*
     * LDH [a8], A
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("LDH *a8, A");
}

void Cpu::instruction_E1_POP()
{
    /*
     * POP HL
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("POP HL");
}

void Cpu::instruction_E2_LDH()
{
    /*
     * LDH [C], A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LDH *C, A");
}

void Cpu::instruction_E5_PUSH()
{
    /*
     * PUSH HL
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("PUSH HL");
}

void Cpu::instruction_E6_AND()
{
    /*
     * AND A, n8
     * Flags: Z 0 1 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("AND A, n8");
}

void Cpu::instruction_E7_RST()
{
    /*
     * RST $20
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 20");
}

void Cpu::instruction_E8_ADD()
{
    /*
     * ADD SP, e8
     * Flags: 0 0 H C
     * Cycles: 16
     */

    current_instruction_asm = std::format("ADD SP, e8");
}

void Cpu::instruction_E9_JP()
{
    /*
     * JP HL
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("JP HL");
}

void Cpu::instruction_EA_LD()
{
    /*
     * LD [a16], A
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("LD *a16, A");
}

void Cpu::instruction_EE_XOR()
{
    /*
     * XOR A, n8
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("XOR A, n8");
}

void Cpu::instruction_EF_RST()
{
    /*
     * RST $28
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 28");
}

void Cpu::instruction_F0_LDH()
{
    /*
     * LDH A, [a8]
     * Flags: - - - -
     * Cycles: 12
     */

    current_instruction_asm = std::format("LDH A, *a8");
}

void Cpu::instruction_F1_POP()
{
    /*
     * POP AF
     * Flags: Z N H C
     * Cycles: 12
     */

    current_instruction_asm = std::format("POP AF");
}

void Cpu::instruction_F2_LDH()
{
    /*
     * LDH A, [C]
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LDH A, *C");
}

void Cpu::instruction_F3_DI()
{
    /*
     * DI
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("DI ");
}

void Cpu::instruction_F5_PUSH()
{
    /*
     * PUSH AF
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("PUSH AF");
}

void Cpu::instruction_F6_OR()
{
    /*
     * OR A, n8
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("OR A, n8");
}

void Cpu::instruction_F7_RST()
{
    /*
     * RST $30
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 30");
}

void Cpu::instruction_F8_LD()
{
    /*
     * LD HL, SP, e8
     * Flags: 0 0 H C
     * Cycles: 12
     */

    current_instruction_asm = std::format("LD HL, SP, e8");
}

void Cpu::instruction_F9_LD()
{
    /*
     * LD SP, HL
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("LD SP, HL");
}

void Cpu::instruction_FA_LD()
{
    /*
     * LD A, [a16]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("LD A, *a16");
}

void Cpu::instruction_FB_EI()
{
    /*
     * EI
     * Flags: - - - -
     * Cycles: 4
     */

    current_instruction_asm = std::format("EI ");
}

void Cpu::instruction_FE_CP()
{
    /*
     * CP A, n8
     * Flags: Z 1 H C
     * Cycles: 8
     */

    current_instruction_asm = std::format("CP A, n8");
}

void Cpu::instruction_FF_RST()
{
    /*
     * RST $38
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RST 38");
}

/*
 * ============================================================================
 * CB-Prefixed Instructions
 * ============================================================================
 */

void Cpu::instruction_CB_00_RLC()
{
    /*
     * RLC B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC B");
}

void Cpu::instruction_CB_01_RLC()
{
    /*
     * RLC C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC C");
}

void Cpu::instruction_CB_02_RLC()
{
    /*
     * RLC D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC D");
}

void Cpu::instruction_CB_03_RLC()
{
    /*
     * RLC E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC E");
}

void Cpu::instruction_CB_04_RLC()
{
    /*
     * RLC H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC H");
}

void Cpu::instruction_CB_05_RLC()
{
    /*
     * RLC L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC L");
}

void Cpu::instruction_CB_06_RLC()
{
    /*
     * RLC [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("RLC !HL");
}

void Cpu::instruction_CB_07_RLC()
{
    /*
     * RLC A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RLC A");
}

void Cpu::instruction_CB_08_RRC()
{
    /*
     * RRC B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC B");
}

void Cpu::instruction_CB_09_RRC()
{
    /*
     * RRC C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC C");
}

void Cpu::instruction_CB_0A_RRC()
{
    /*
     * RRC D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC D");
}

void Cpu::instruction_CB_0B_RRC()
{
    /*
     * RRC E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC E");
}

void Cpu::instruction_CB_0C_RRC()
{
    /*
     * RRC H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC H");
}

void Cpu::instruction_CB_0D_RRC()
{
    /*
     * RRC L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC L");
}

void Cpu::instruction_CB_0E_RRC()
{
    /*
     * RRC [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("RRC !HL");
}

void Cpu::instruction_CB_0F_RRC()
{
    /*
     * RRC A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RRC A");
}

void Cpu::instruction_CB_10_RL()
{
    /*
     * RL B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL B");
}

void Cpu::instruction_CB_11_RL()
{
    /*
     * RL C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL C");
}

void Cpu::instruction_CB_12_RL()
{
    /*
     * RL D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL D");
}

void Cpu::instruction_CB_13_RL()
{
    /*
     * RL E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL E");
}

void Cpu::instruction_CB_14_RL()
{
    /*
     * RL H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL H");
}

void Cpu::instruction_CB_15_RL()
{
    /*
     * RL L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL L");
}

void Cpu::instruction_CB_16_RL()
{
    /*
     * RL [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("RL !HL");
}

void Cpu::instruction_CB_17_RL()
{
    /*
     * RL A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RL A");
}

void Cpu::instruction_CB_18_RR()
{
    /*
     * RR B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR B");
}

void Cpu::instruction_CB_19_RR()
{
    /*
     * RR C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR C");
}

void Cpu::instruction_CB_1A_RR()
{
    /*
     * RR D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR D");
}

void Cpu::instruction_CB_1B_RR()
{
    /*
     * RR E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR E");
}

void Cpu::instruction_CB_1C_RR()
{
    /*
     * RR H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR H");
}

void Cpu::instruction_CB_1D_RR()
{
    /*
     * RR L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR L");
}

void Cpu::instruction_CB_1E_RR()
{
    /*
     * RR [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("RR !HL");
}

void Cpu::instruction_CB_1F_RR()
{
    /*
     * RR A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("RR A");
}

void Cpu::instruction_CB_20_SLA()
{
    /*
     * SLA B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA B");
}

void Cpu::instruction_CB_21_SLA()
{
    /*
     * SLA C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA C");
}

void Cpu::instruction_CB_22_SLA()
{
    /*
     * SLA D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA D");
}

void Cpu::instruction_CB_23_SLA()
{
    /*
     * SLA E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA E");
}

void Cpu::instruction_CB_24_SLA()
{
    /*
     * SLA H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA H");
}

void Cpu::instruction_CB_25_SLA()
{
    /*
     * SLA L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA L");
}

void Cpu::instruction_CB_26_SLA()
{
    /*
     * SLA [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("SLA !HL");
}

void Cpu::instruction_CB_27_SLA()
{
    /*
     * SLA A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SLA A");
}

void Cpu::instruction_CB_28_SRA()
{
    /*
     * SRA B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA B");
}

void Cpu::instruction_CB_29_SRA()
{
    /*
     * SRA C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA C");
}

void Cpu::instruction_CB_2A_SRA()
{
    /*
     * SRA D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA D");
}

void Cpu::instruction_CB_2B_SRA()
{
    /*
     * SRA E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA E");
}

void Cpu::instruction_CB_2C_SRA()
{
    /*
     * SRA H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA H");
}

void Cpu::instruction_CB_2D_SRA()
{
    /*
     * SRA L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA L");
}

void Cpu::instruction_CB_2E_SRA()
{
    /*
     * SRA [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("SRA !HL");
}

void Cpu::instruction_CB_2F_SRA()
{
    /*
     * SRA A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRA A");
}

void Cpu::instruction_CB_30_SWAP()
{
    /*
     * SWAP B
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP B");
}

void Cpu::instruction_CB_31_SWAP()
{
    /*
     * SWAP C
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP C");
}

void Cpu::instruction_CB_32_SWAP()
{
    /*
     * SWAP D
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP D");
}

void Cpu::instruction_CB_33_SWAP()
{
    /*
     * SWAP E
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP E");
}

void Cpu::instruction_CB_34_SWAP()
{
    /*
     * SWAP H
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP H");
}

void Cpu::instruction_CB_35_SWAP()
{
    /*
     * SWAP L
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP L");
}

void Cpu::instruction_CB_36_SWAP()
{
    /*
     * SWAP [HL]
     * Flags: Z 0 0 0
     * Cycles: 16
     */

    current_instruction_asm = std::format("SWAP !HL");
}

void Cpu::instruction_CB_37_SWAP()
{
    /*
     * SWAP A
     * Flags: Z 0 0 0
     * Cycles: 8
     */

    current_instruction_asm = std::format("SWAP A");
}

void Cpu::instruction_CB_38_SRL()
{
    /*
     * SRL B
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL B");
}

void Cpu::instruction_CB_39_SRL()
{
    /*
     * SRL C
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL C");
}

void Cpu::instruction_CB_3A_SRL()
{
    /*
     * SRL D
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL D");
}

void Cpu::instruction_CB_3B_SRL()
{
    /*
     * SRL E
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL E");
}

void Cpu::instruction_CB_3C_SRL()
{
    /*
     * SRL H
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL H");
}

void Cpu::instruction_CB_3D_SRL()
{
    /*
     * SRL L
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL L");
}

void Cpu::instruction_CB_3E_SRL()
{
    /*
     * SRL [HL]
     * Flags: Z 0 0 C
     * Cycles: 16
     */

    current_instruction_asm = std::format("SRL !HL");
}

void Cpu::instruction_CB_3F_SRL()
{
    /*
     * SRL A
     * Flags: Z 0 0 C
     * Cycles: 8
     */

    current_instruction_asm = std::format("SRL A");
}

void Cpu::instruction_CB_40_BIT()
{
    /*
     * BIT 0, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, B");
}

void Cpu::instruction_CB_41_BIT()
{
    /*
     * BIT 0, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, C");
}

void Cpu::instruction_CB_42_BIT()
{
    /*
     * BIT 0, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, D");
}

void Cpu::instruction_CB_43_BIT()
{
    /*
     * BIT 0, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, E");
}

void Cpu::instruction_CB_44_BIT()
{
    /*
     * BIT 0, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, H");
}

void Cpu::instruction_CB_45_BIT()
{
    /*
     * BIT 0, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, L");
}

void Cpu::instruction_CB_46_BIT()
{
    /*
     * BIT 0, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 0, !HL");
}

void Cpu::instruction_CB_47_BIT()
{
    /*
     * BIT 0, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 0, A");
}

void Cpu::instruction_CB_48_BIT()
{
    /*
     * BIT 1, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, B");
}

void Cpu::instruction_CB_49_BIT()
{
    /*
     * BIT 1, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, C");
}

void Cpu::instruction_CB_4A_BIT()
{
    /*
     * BIT 1, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, D");
}

void Cpu::instruction_CB_4B_BIT()
{
    /*
     * BIT 1, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, E");
}

void Cpu::instruction_CB_4C_BIT()
{
    /*
     * BIT 1, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, H");
}

void Cpu::instruction_CB_4D_BIT()
{
    /*
     * BIT 1, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, L");
}

void Cpu::instruction_CB_4E_BIT()
{
    /*
     * BIT 1, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 1, !HL");
}

void Cpu::instruction_CB_4F_BIT()
{
    /*
     * BIT 1, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 1, A");
}

void Cpu::instruction_CB_50_BIT()
{
    /*
     * BIT 2, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, B");
}

void Cpu::instruction_CB_51_BIT()
{
    /*
     * BIT 2, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, C");
}

void Cpu::instruction_CB_52_BIT()
{
    /*
     * BIT 2, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, D");
}

void Cpu::instruction_CB_53_BIT()
{
    /*
     * BIT 2, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, E");
}

void Cpu::instruction_CB_54_BIT()
{
    /*
     * BIT 2, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, H");
}

void Cpu::instruction_CB_55_BIT()
{
    /*
     * BIT 2, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, L");
}

void Cpu::instruction_CB_56_BIT()
{
    /*
     * BIT 2, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 2, !HL");
}

void Cpu::instruction_CB_57_BIT()
{
    /*
     * BIT 2, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 2, A");
}

void Cpu::instruction_CB_58_BIT()
{
    /*
     * BIT 3, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, B");
}

void Cpu::instruction_CB_59_BIT()
{
    /*
     * BIT 3, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, C");
}

void Cpu::instruction_CB_5A_BIT()
{
    /*
     * BIT 3, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, D");
}

void Cpu::instruction_CB_5B_BIT()
{
    /*
     * BIT 3, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, E");
}

void Cpu::instruction_CB_5C_BIT()
{
    /*
     * BIT 3, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, H");
}

void Cpu::instruction_CB_5D_BIT()
{
    /*
     * BIT 3, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, L");
}

void Cpu::instruction_CB_5E_BIT()
{
    /*
     * BIT 3, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 3, !HL");
}

void Cpu::instruction_CB_5F_BIT()
{
    /*
     * BIT 3, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 3, A");
}

void Cpu::instruction_CB_60_BIT()
{
    /*
     * BIT 4, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, B");
}

void Cpu::instruction_CB_61_BIT()
{
    /*
     * BIT 4, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, C");
}

void Cpu::instruction_CB_62_BIT()
{
    /*
     * BIT 4, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, D");
}

void Cpu::instruction_CB_63_BIT()
{
    /*
     * BIT 4, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, E");
}

void Cpu::instruction_CB_64_BIT()
{
    /*
     * BIT 4, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, H");
}

void Cpu::instruction_CB_65_BIT()
{
    /*
     * BIT 4, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, L");
}

void Cpu::instruction_CB_66_BIT()
{
    /*
     * BIT 4, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 4, !HL");
}

void Cpu::instruction_CB_67_BIT()
{
    /*
     * BIT 4, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 4, A");
}

void Cpu::instruction_CB_68_BIT()
{
    /*
     * BIT 5, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, B");
}

void Cpu::instruction_CB_69_BIT()
{
    /*
     * BIT 5, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, C");
}

void Cpu::instruction_CB_6A_BIT()
{
    /*
     * BIT 5, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, D");
}

void Cpu::instruction_CB_6B_BIT()
{
    /*
     * BIT 5, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, E");
}

void Cpu::instruction_CB_6C_BIT()
{
    /*
     * BIT 5, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, H");
}

void Cpu::instruction_CB_6D_BIT()
{
    /*
     * BIT 5, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, L");
}

void Cpu::instruction_CB_6E_BIT()
{
    /*
     * BIT 5, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 5, !HL");
}

void Cpu::instruction_CB_6F_BIT()
{
    /*
     * BIT 5, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 5, A");
}

void Cpu::instruction_CB_70_BIT()
{
    /*
     * BIT 6, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, B");
}

void Cpu::instruction_CB_71_BIT()
{
    /*
     * BIT 6, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, C");
}

void Cpu::instruction_CB_72_BIT()
{
    /*
     * BIT 6, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, D");
}

void Cpu::instruction_CB_73_BIT()
{
    /*
     * BIT 6, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, E");
}

void Cpu::instruction_CB_74_BIT()
{
    /*
     * BIT 6, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, H");
}

void Cpu::instruction_CB_75_BIT()
{
    /*
     * BIT 6, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, L");
}

void Cpu::instruction_CB_76_BIT()
{
    /*
     * BIT 6, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 6, !HL");
}

void Cpu::instruction_CB_77_BIT()
{
    /*
     * BIT 6, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 6, A");
}

void Cpu::instruction_CB_78_BIT()
{
    /*
     * BIT 7, B
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, B");
}

void Cpu::instruction_CB_79_BIT()
{
    /*
     * BIT 7, C
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, C");
}

void Cpu::instruction_CB_7A_BIT()
{
    /*
     * BIT 7, D
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, D");
}

void Cpu::instruction_CB_7B_BIT()
{
    /*
     * BIT 7, E
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, E");
}

void Cpu::instruction_CB_7C_BIT()
{
    /*
     * BIT 7, H
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, H");
}

void Cpu::instruction_CB_7D_BIT()
{
    /*
     * BIT 7, L
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, L");
}

void Cpu::instruction_CB_7E_BIT()
{
    /*
     * BIT 7, [HL]
     * Flags: Z 0 1 -
     * Cycles: 12
     */

    current_instruction_asm = std::format("BIT 7, !HL");
}

void Cpu::instruction_CB_7F_BIT()
{
    /*
     * BIT 7, A
     * Flags: Z 0 1 -
     * Cycles: 8
     */

    current_instruction_asm = std::format("BIT 7, A");
}

void Cpu::instruction_CB_80_RES()
{
    /*
     * RES 0, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, B");
}

void Cpu::instruction_CB_81_RES()
{
    /*
     * RES 0, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, C");
}

void Cpu::instruction_CB_82_RES()
{
    /*
     * RES 0, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, D");
}

void Cpu::instruction_CB_83_RES()
{
    /*
     * RES 0, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, E");
}

void Cpu::instruction_CB_84_RES()
{
    /*
     * RES 0, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, H");
}

void Cpu::instruction_CB_85_RES()
{
    /*
     * RES 0, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, L");
}

void Cpu::instruction_CB_86_RES()
{
    /*
     * RES 0, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 0, !HL");
}

void Cpu::instruction_CB_87_RES()
{
    /*
     * RES 0, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 0, A");
}

void Cpu::instruction_CB_88_RES()
{
    /*
     * RES 1, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, B");
}

void Cpu::instruction_CB_89_RES()
{
    /*
     * RES 1, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, C");
}

void Cpu::instruction_CB_8A_RES()
{
    /*
     * RES 1, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, D");
}

void Cpu::instruction_CB_8B_RES()
{
    /*
     * RES 1, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, E");
}

void Cpu::instruction_CB_8C_RES()
{
    /*
     * RES 1, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, H");
}

void Cpu::instruction_CB_8D_RES()
{
    /*
     * RES 1, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, L");
}

void Cpu::instruction_CB_8E_RES()
{
    /*
     * RES 1, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 1, !HL");
}

void Cpu::instruction_CB_8F_RES()
{
    /*
     * RES 1, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 1, A");
}

void Cpu::instruction_CB_90_RES()
{
    /*
     * RES 2, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, B");
}

void Cpu::instruction_CB_91_RES()
{
    /*
     * RES 2, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, C");
}

void Cpu::instruction_CB_92_RES()
{
    /*
     * RES 2, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, D");
}

void Cpu::instruction_CB_93_RES()
{
    /*
     * RES 2, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, E");
}

void Cpu::instruction_CB_94_RES()
{
    /*
     * RES 2, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, H");
}

void Cpu::instruction_CB_95_RES()
{
    /*
     * RES 2, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, L");
}

void Cpu::instruction_CB_96_RES()
{
    /*
     * RES 2, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 2, !HL");
}

void Cpu::instruction_CB_97_RES()
{
    /*
     * RES 2, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 2, A");
}

void Cpu::instruction_CB_98_RES()
{
    /*
     * RES 3, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, B");
}

void Cpu::instruction_CB_99_RES()
{
    /*
     * RES 3, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, C");
}

void Cpu::instruction_CB_9A_RES()
{
    /*
     * RES 3, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, D");
}

void Cpu::instruction_CB_9B_RES()
{
    /*
     * RES 3, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, E");
}

void Cpu::instruction_CB_9C_RES()
{
    /*
     * RES 3, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, H");
}

void Cpu::instruction_CB_9D_RES()
{
    /*
     * RES 3, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, L");
}

void Cpu::instruction_CB_9E_RES()
{
    /*
     * RES 3, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 3, !HL");
}

void Cpu::instruction_CB_9F_RES()
{
    /*
     * RES 3, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 3, A");
}

void Cpu::instruction_CB_A0_RES()
{
    /*
     * RES 4, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, B");
}

void Cpu::instruction_CB_A1_RES()
{
    /*
     * RES 4, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, C");
}

void Cpu::instruction_CB_A2_RES()
{
    /*
     * RES 4, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, D");
}

void Cpu::instruction_CB_A3_RES()
{
    /*
     * RES 4, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, E");
}

void Cpu::instruction_CB_A4_RES()
{
    /*
     * RES 4, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, H");
}

void Cpu::instruction_CB_A5_RES()
{
    /*
     * RES 4, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, L");
}

void Cpu::instruction_CB_A6_RES()
{
    /*
     * RES 4, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 4, !HL");
}

void Cpu::instruction_CB_A7_RES()
{
    /*
     * RES 4, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 4, A");
}

void Cpu::instruction_CB_A8_RES()
{
    /*
     * RES 5, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, B");
}

void Cpu::instruction_CB_A9_RES()
{
    /*
     * RES 5, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, C");
}

void Cpu::instruction_CB_AA_RES()
{
    /*
     * RES 5, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, D");
}

void Cpu::instruction_CB_AB_RES()
{
    /*
     * RES 5, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, E");
}

void Cpu::instruction_CB_AC_RES()
{
    /*
     * RES 5, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, H");
}

void Cpu::instruction_CB_AD_RES()
{
    /*
     * RES 5, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, L");
}

void Cpu::instruction_CB_AE_RES()
{
    /*
     * RES 5, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 5, !HL");
}

void Cpu::instruction_CB_AF_RES()
{
    /*
     * RES 5, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 5, A");
}

void Cpu::instruction_CB_B0_RES()
{
    /*
     * RES 6, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, B");
}

void Cpu::instruction_CB_B1_RES()
{
    /*
     * RES 6, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, C");
}

void Cpu::instruction_CB_B2_RES()
{
    /*
     * RES 6, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, D");
}

void Cpu::instruction_CB_B3_RES()
{
    /*
     * RES 6, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, E");
}

void Cpu::instruction_CB_B4_RES()
{
    /*
     * RES 6, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, H");
}

void Cpu::instruction_CB_B5_RES()
{
    /*
     * RES 6, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, L");
}

void Cpu::instruction_CB_B6_RES()
{
    /*
     * RES 6, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 6, !HL");
}

void Cpu::instruction_CB_B7_RES()
{
    /*
     * RES 6, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 6, A");
}

void Cpu::instruction_CB_B8_RES()
{
    /*
     * RES 7, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, B");
}

void Cpu::instruction_CB_B9_RES()
{
    /*
     * RES 7, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, C");
}

void Cpu::instruction_CB_BA_RES()
{
    /*
     * RES 7, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, D");
}

void Cpu::instruction_CB_BB_RES()
{
    /*
     * RES 7, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, E");
}

void Cpu::instruction_CB_BC_RES()
{
    /*
     * RES 7, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, H");
}

void Cpu::instruction_CB_BD_RES()
{
    /*
     * RES 7, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, L");
}

void Cpu::instruction_CB_BE_RES()
{
    /*
     * RES 7, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("RES 7, !HL");
}

void Cpu::instruction_CB_BF_RES()
{
    /*
     * RES 7, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("RES 7, A");
}

void Cpu::instruction_CB_C0_SET()
{
    /*
     * SET 0, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, B");
}

void Cpu::instruction_CB_C1_SET()
{
    /*
     * SET 0, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, C");
}

void Cpu::instruction_CB_C2_SET()
{
    /*
     * SET 0, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, D");
}

void Cpu::instruction_CB_C3_SET()
{
    /*
     * SET 0, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, E");
}

void Cpu::instruction_CB_C4_SET()
{
    /*
     * SET 0, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, H");
}

void Cpu::instruction_CB_C5_SET()
{
    /*
     * SET 0, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, L");
}

void Cpu::instruction_CB_C6_SET()
{
    /*
     * SET 0, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 0, !HL");
}

void Cpu::instruction_CB_C7_SET()
{
    /*
     * SET 0, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 0, A");
}

void Cpu::instruction_CB_C8_SET()
{
    /*
     * SET 1, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, B");
}

void Cpu::instruction_CB_C9_SET()
{
    /*
     * SET 1, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, C");
}

void Cpu::instruction_CB_CA_SET()
{
    /*
     * SET 1, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, D");
}

void Cpu::instruction_CB_CB_SET()
{
    /*
     * SET 1, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, E");
}

void Cpu::instruction_CB_CC_SET()
{
    /*
     * SET 1, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, H");
}

void Cpu::instruction_CB_CD_SET()
{
    /*
     * SET 1, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, L");
}

void Cpu::instruction_CB_CE_SET()
{
    /*
     * SET 1, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 1, !HL");
}

void Cpu::instruction_CB_CF_SET()
{
    /*
     * SET 1, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 1, A");
}

void Cpu::instruction_CB_D0_SET()
{
    /*
     * SET 2, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, B");
}

void Cpu::instruction_CB_D1_SET()
{
    /*
     * SET 2, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, C");
}

void Cpu::instruction_CB_D2_SET()
{
    /*
     * SET 2, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, D");
}

void Cpu::instruction_CB_D3_SET()
{
    /*
     * SET 2, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, E");
}

void Cpu::instruction_CB_D4_SET()
{
    /*
     * SET 2, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, H");
}

void Cpu::instruction_CB_D5_SET()
{
    /*
     * SET 2, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, L");
}

void Cpu::instruction_CB_D6_SET()
{
    /*
     * SET 2, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 2, !HL");
}

void Cpu::instruction_CB_D7_SET()
{
    /*
     * SET 2, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 2, A");
}

void Cpu::instruction_CB_D8_SET()
{
    /*
     * SET 3, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, B");
}

void Cpu::instruction_CB_D9_SET()
{
    /*
     * SET 3, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, C");
}

void Cpu::instruction_CB_DA_SET()
{
    /*
     * SET 3, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, D");
}

void Cpu::instruction_CB_DB_SET()
{
    /*
     * SET 3, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, E");
}

void Cpu::instruction_CB_DC_SET()
{
    /*
     * SET 3, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, H");
}

void Cpu::instruction_CB_DD_SET()
{
    /*
     * SET 3, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, L");
}

void Cpu::instruction_CB_DE_SET()
{
    /*
     * SET 3, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 3, !HL");
}

void Cpu::instruction_CB_DF_SET()
{
    /*
     * SET 3, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 3, A");
}

void Cpu::instruction_CB_E0_SET()
{
    /*
     * SET 4, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, B");
}

void Cpu::instruction_CB_E1_SET()
{
    /*
     * SET 4, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, C");
}

void Cpu::instruction_CB_E2_SET()
{
    /*
     * SET 4, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, D");
}

void Cpu::instruction_CB_E3_SET()
{
    /*
     * SET 4, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, E");
}

void Cpu::instruction_CB_E4_SET()
{
    /*
     * SET 4, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, H");
}

void Cpu::instruction_CB_E5_SET()
{
    /*
     * SET 4, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, L");
}

void Cpu::instruction_CB_E6_SET()
{
    /*
     * SET 4, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 4, !HL");
}

void Cpu::instruction_CB_E7_SET()
{
    /*
     * SET 4, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 4, A");
}

void Cpu::instruction_CB_E8_SET()
{
    /*
     * SET 5, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, B");
}

void Cpu::instruction_CB_E9_SET()
{
    /*
     * SET 5, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, C");
}

void Cpu::instruction_CB_EA_SET()
{
    /*
     * SET 5, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, D");
}

void Cpu::instruction_CB_EB_SET()
{
    /*
     * SET 5, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, E");
}

void Cpu::instruction_CB_EC_SET()
{
    /*
     * SET 5, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, H");
}

void Cpu::instruction_CB_ED_SET()
{
    /*
     * SET 5, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, L");
}

void Cpu::instruction_CB_EE_SET()
{
    /*
     * SET 5, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 5, !HL");
}

void Cpu::instruction_CB_EF_SET()
{
    /*
     * SET 5, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 5, A");
}

void Cpu::instruction_CB_F0_SET()
{
    /*
     * SET 6, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, B");
}

void Cpu::instruction_CB_F1_SET()
{
    /*
     * SET 6, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, C");
}

void Cpu::instruction_CB_F2_SET()
{
    /*
     * SET 6, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, D");
}

void Cpu::instruction_CB_F3_SET()
{
    /*
     * SET 6, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, E");
}

void Cpu::instruction_CB_F4_SET()
{
    /*
     * SET 6, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, H");
}

void Cpu::instruction_CB_F5_SET()
{
    /*
     * SET 6, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, L");
}

void Cpu::instruction_CB_F6_SET()
{
    /*
     * SET 6, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 6, !HL");
}

void Cpu::instruction_CB_F7_SET()
{
    /*
     * SET 6, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 6, A");
}

void Cpu::instruction_CB_F8_SET()
{
    /*
     * SET 7, B
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, B");
}

void Cpu::instruction_CB_F9_SET()
{
    /*
     * SET 7, C
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, C");
}

void Cpu::instruction_CB_FA_SET()
{
    /*
     * SET 7, D
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, D");
}

void Cpu::instruction_CB_FB_SET()
{
    /*
     * SET 7, E
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, E");
}

void Cpu::instruction_CB_FC_SET()
{
    /*
     * SET 7, H
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, H");
}

void Cpu::instruction_CB_FD_SET()
{
    /*
     * SET 7, L
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, L");
}

void Cpu::instruction_CB_FE_SET()
{
    /*
     * SET 7, [HL]
     * Flags: - - - -
     * Cycles: 16
     */

    current_instruction_asm = std::format("SET 7, !HL");
}

void Cpu::instruction_CB_FF_SET()
{
    /*
     * SET 7, A
     * Flags: - - - -
     * Cycles: 8
     */

    current_instruction_asm = std::format("SET 7, A");
}

} // namespace Gbpp::Backend
